### Aca alojamos todos los protocolos HTTP relacionados a los usuarios

### Obtener todos los usuarios
GET http://localhost:3000/api/usuarios

### Obtener un usuario por ID
GET http://localhost:3000/api/usuarios/1

### Crear un nuevo usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "name": "ricardo",
    "email": "ricardito@gmail.com",
    "password": "passwordGenerica"
}

### Actualizar un usuario existente
PUT http://localhost:3000/api/usuarios/1
Content-Type: application/json

{
    "name": "sebas updated",
    "email": "sebas.updated@gmail.com",
    "password": "updatedsebpassword123"
}

### Eliminar un usuario
DELETE http://localhost:3000/api/usuarios/4